# Generated by Django 2.1.4 on 2019-01-10 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
